oratest:
    wallet: src/main/resources/wallet

spring:
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@your_tns_alias_high?TNS_ADMIN=${oratest.wallet}
        username: HR
        password: YOUR_HR_PASSWORD
        type: oracle.jdbc.datasource.impl.OracleDataSource
        oracleucp:
            connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
            sql-for-validate-connection: select * from dual
            connection-pool-name: connectionPoolName1
            initial-pool-size: 15
            min-pool-size: 10
            max-pool-size: 30
    jpa:
        database-platform: org.hibernate.dialect.OracleDialect

logging:
    level:
        root: debug
        oracle.ucp: debug
    file:
        name: logs.log